create table tb03_users
(
    id       bigint generated by default as identity,
    username varchar(50)  not null,
    password varchar(500) not null,
    enabled  boolean      not null,
    primary key (id)
);

insert into tb03_users (id, username, password, enabled)
values (default, 'admin', '$2a$10$lCl75SOeP0s5oPnqb2.M8.UpCxkf.JJUWPVdHYtdapElpG/H0ABae', true);