create table tb04_authorities (
   id bigint generated by default as identity,
   user_id bigint not null,
   authority varchar(50) not null,
   primary key (id),
   constraint fk_authorities_users foreign key(user_id) references tb03_users(id)
);
