create table tb04_authorities
(
    id         bigint generated by default as identity,
    id_usuario bigint      not null,
    nome       varchar(50) not null,
    primary key (id),
    constraint fk_authorities_users foreign key (id_usuario) references tb03_login (id)
);


insert into tb04_authorities (id, id_usuario, nome)
values (default, (select l.id from tb03_login l where l.username = 'admin'), 'produto:cadastro');